### ISSUE TITLE
Refactor: per-workspace dependencies for proper monorepo isolation

### ISSUE THREAD

**Issue by emaarco** [Miragon/bpmn-vscode-modeler#944]
## Context

Discovered while planning a Linux-build-deps fix on PR #924: this monorepo currently has **all 54 dependencies hoisted to the root `package.json`**. Individual workspace `package.json` files (`apps/modeler-plugin`, `apps/bpmn-webview`, etc.) have **no `dependencies` and no `devDependencies` fields at all** — they only declare scripts.

This means CI workflows can't take advantage of Yarn 4's `yarn workspaces focus <name>`, which would otherwise install only the dep tree for one specific workspace. Today, **every workflow that runs `yarn install` pulls in everything** — including the heavy Theia + native-keymap deps from `apps/standalone/`, even when building unrelated artefacts.

## The current pain

After PR #924 merges, this surfaces as a real issue:

- `apps/standalone/` legitimately requires `native-keymap@2.5.0` (transitive via `@theia/core`).
- `native-keymap`'s postinstall calls `node-gyp` which needs `libx11-dev` / `libxkbfile-dev` on Linux runners.
- `build.yml` already installs those via apt. But `release.yml`, `release-create-append-c7.yml`, `deploy-docs.yml` also do `yarn install` and would fail without those system deps.
- We worked around it by adding the apt-step to all four Linux workflows. **It works, but it's a recurring tax** — every new Linux workflow has to remember it, and CI runtime grows by 30–60 s per run.

## What proper isolation would look like

Move root-level dependencies into the workspaces that actually use them. Then:

| Workflow | Install command | Effect |
|---|---|---|
| `release.yml` (modeler-plugin) | `yarn workspaces focus vs-code-bpmn-modeler` | Only modeler-plugin's deps + its workspace-deps. No Theia, no native-keymap → no apt step needed. |
| `release-create-append-c7.yml` (npm lib) | `yarn workspaces focus @bpmn-modeler/create-append-c7-element-templates` | Just the lib + `@bpmn-modeler/shared`. Sub-second install. |
| `release-standalone.yml` (DMG) | `yarn workspaces focus standalone` | Only Theia stuff, runs on macOS so still no system-deps issue. |
| `deploy-docs.yml` (VitePress) | `yarn workspaces focus docs` | Only VitePress + theme. Tiny install. |
| `build.yml` (full repo) | `yarn install --immutable` (unchanged) | Full sweep — apt-step required. |

## Effort & risk

This is a **non-trivial refactor**:

1. Audit which deps each workspace actually `import`s.
2. Move shared deps (e.g., `webpack-cli`, `ts-loader`, `jest`, `eslint`) into the workspaces that use them. Some will end up in multiple workspaces — Yarn's dedup handles that.
3. Confirm root keeps only deps that are truly cross-cutting (e.g., `npm-run-all` if it orchestrates).
4. Update CI workflows to use `yarn workspaces focus` (per the table above).
5. Run all four pipelines as dry-run to verify.

Risks: webpack/ts-loader/jest tooling needs to resolve from the right place; it's easy to break a build by missing a dep. Per-workspace tsconfig may need adjustment.

## Why it's worth doing

- **Eliminates the apt-step tax** in 3 (and potentially future) Linux workflows.
- **Faster CI** for each release pipeline (~30–60 s per run).
- **Architectural cleanup**: each workspace's `package.json` honestly declares what it needs.
- **Scales for future deliverables**: a Windows standalone, a new app workspace, a new lib — the existing pipelines stay unaffected by what they ship.
- **Better local dev story** for new contributors: `yarn workspaces focus modeler-plugin` for plugin-only work, no Theia install.

## Out of scope for this issue

- Splitting the repo into multiple repos (much bigger move).
- Moving from `nodeLinker: node-modules` to PnP.

## Related

- Discovered during PR #924 (Theia standalone spike) — see [the conversation around the apt-step fix](https://github.com/Miragon/bpmn-vscode-modeler/pull/924).
- The current apt-step workaround keeps things working until this lands.

---

## Side note: pre-existing c7 release build break

While dry-running the existing `release-create-append-c7.yml` workflow (to validate the install-step fix in PR #924), the **library build step itself** failed independently:

```
tsconfig.lib.json(3,5): error TS5101: Option 'baseUrl' is deprecated and will stop functioning in TypeScript 7.0
tsconfig.lib.json(3,5): error TS5107: Option 'moduleResolution=node10' is deprecated and will stop functioning in TypeScript 7.0
```

This is **not caused by PR #924** — it's pre-existing on `main`. The c7 release workflow is `workflow_dispatch` only, so it hadn't been triggered since TypeScript started rejecting these deprecations.

Smallest fix: add `"ignoreDeprecations": "6.0"` to `libs/create-append-c7-element-templates/tsconfig.lib.json`, OR remove `baseUrl` + replace `moduleResolution: "node10"` with `"bundler"` or `"node16"`.

Worth bundling into the workspace-isolation refactor described above, since `tsconfig.lib.json` per-workspace will likely be touched anyway.
